# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test KNXVI .NET

on:
  push:
    branches: [ "main", "ElDiabolotino-Solving-CI-issues" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: windows-latest
    defaults:
      run:
        working-directory: './KNX Virtual Integrator/'
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: 'true'
        cache-dependency-path: './KNX Virtual Integrator/package-lock.json'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --no-restore
    - name: Workload Update
      run: dotnet workload list
    - name: Test 
      run: dotnet test --no-build --verbosity normal  
    
